language: python

sudo: false

env:
  - TOX_ENV=py27-latest
  - TOX_ENV=py34-latest
  # Django 1.8
  - TOX_ENV=py27-dj18-cms34
  - TOX_ENV=py27-dj18-cms33
  - TOX_ENV=py34-dj18-cms34
  - TOX_ENV=py34-dj18-cms33
  # Django 1.9
  - TOX_ENV=py27-dj19-cms34
  - TOX_ENV=py27-dj19-cms33
  - TOX_ENV=py34-dj19-cms34
  - TOX_ENV=py34-dj19-cms33

install:
  - pip install -r requirements-test.txt
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
    coveralls